#!/bin/bash

cd
echo ""
echo "allow file access to proceed"
termux-setup-storage & sleep 5 &>/dev/null

while true; do
    if [ -e storage ]; then
        rm -rf /sdcard/winux
        break
    else
        echo "if u denied permission turn on it by yourself"
    fi
    sleep 2
done

mkdir -p /sdcard/winux

echo ""
echo "please wait while i'm updating ur termux"
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1

echo ""
echo "installing needed files"
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install proot -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null

rm -rf $HOME/winux
mkdir -p $HOME/winux
cd $HOME/winux

wget https://github.com/olegos2/winux/raw/main/components/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb

echo "downloading rootfs..."
cd $HOME/winux
wget -q --show-progress https://github.com/yamahich/winux/releases/download/0.0.1-alpha/rootfs.tar.xz


echo "Unzipping Rootfs..."
tar -xf rootfs.tar.xz
rm -rf rootfs.tar.xz

cd $HOME/winux/ubuntu-fs/opt
wget https://github.com/yamahich1337/winux/raw/main/scripts/scripts.tar.gz &>/dev/null
tar -xf scripts.tar.gz
rm -rf scripts.tar.gz

cd $HOME/winux/
wget -N https://github.com/olegos2/winux/raw/main/scripts/winux &>/dev/null
chmod +x winux
mv winux $PREFIX/bin/
wget -N https://github.com/olegos2/winux/raw/main/scripts/start-proot.sh &>/dev/null
wget -N https://github.com/olegos2/winux/raw/main/scripts/start-chroot.sh &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

echo "Installing patch"

cd $HOME/winux/ubuntu-fs
wget -q --show-progress https://github.com/olegos2/winux/releases/download/0.0.1-alpha/patch.tar.xz
rm -rf opt/d3d
rm -rf opt/mesa
tar -xf patch.tar.xz
rm -rf patch.tar.xz
cd

echo "Starting winux now. Next time use \"winux\" command to run it."
sleep 2

rm -rf "$0"


exec $PREFIX/bin/winux
